/**
 * @NApiVersion 2.1
 * @NScriptType MapReduceScript
 * @NModuleScope SameAccount
 */

define(['N/record', 'N/search', 'N/log'], (record, search, log) => {

    const getInputData = () => {
        // You can replace this with a saved search or custom search
        // Example: search.load({ id: 'customsearch_customer_update_list' })
        return [
{ internalId: 56203, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56045, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55813, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55960, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55926, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55877, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56283, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55943, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55892, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56144, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56237, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56251, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55882, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56277, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56305, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56059, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55811, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55814, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56232, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55969, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55903, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55815, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55914, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56248, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55867, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56008, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55881, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55897, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55816, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55806, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56151, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56080, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56065, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55889, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55902, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56297, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55817, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56006, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55890, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56270, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55876, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56250, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56204, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56180, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56229, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55956, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56094, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56128, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56258, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55922, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55992, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55996, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55991, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56081, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55818, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56077, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56023, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55819, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55820, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56111, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56010, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56147, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56211, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55821, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56190, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56038, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56024, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55822, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56276, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55823, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55937, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55941, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55953, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56022, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55900, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56177, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56281, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56223, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56292, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55931, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55898, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56142, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55899, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56173, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56143, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56214, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56109, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56103, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56134, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55799, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56278, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55824, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56146, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56051, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55880, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55825, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55940, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56017, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55826, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55868, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55827, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55828, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55948, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56262, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55829, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55831, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56155, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55832, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55958, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55951, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56123, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55800, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56159, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56085, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56110, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56265, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56269, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56139, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56130, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56287, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56225, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55833, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56087, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55896, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56187, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56296, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55834, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56274, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56198, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56206, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56167, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55835, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55836, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55895, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55837, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55883, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55946, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56046, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56104, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55839, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56140, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56216, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56242, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56035, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55887, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56240, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56148, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56021, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56132, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55935, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55925, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55840, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56268, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55988, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56093, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56212, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56200, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56011, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56168, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56073, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56238, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56230, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55997, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56215, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56133, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56016, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56079, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56118, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55888, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56275, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56145, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56089, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56241, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56170, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56166, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56013, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56184, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56245, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55930, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56047, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55995, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56163, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56208, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56076, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55966, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55962, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56117, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56220, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55999, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56071, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56070, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56112, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55878, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56012, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56194, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56031, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56205, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55869, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56040, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56060, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56105, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56300, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56055, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56066, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56196, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55797, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56235, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56028, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55795, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56086, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55981, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56113, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55801, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55916, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56074, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56252, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56039, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56092, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55957, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56257, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56249, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56260, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56052, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55973, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56290, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55954, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55875, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55906, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55907, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56226, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55909, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55927, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56042, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55841, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55918, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55870, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55901, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55885, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56137, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55842, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55844, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56108, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55976, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56083, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55989, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56072, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56236, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55802, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56154, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55986, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55845, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55908, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55846, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56041, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55919, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56068, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55894, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56057, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56119, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55847, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56032, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55963, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55848, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55803, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55849, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55979, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56222, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55936, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55913, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56282, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55990, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56075, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56213, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56192, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56043, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56266, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55952, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56091, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56172, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55807, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56171, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56078, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56945, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55850, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56098, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56157, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56026, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56224, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56181, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56271, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56207, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55942, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56138, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56294, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55921, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56136, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56284, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56202, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56189, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56102, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56304, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55968, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55961, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56058, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55805, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55938, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55984, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56299, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56221, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55910, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56033, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55796, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55886, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56179, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55939, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56088, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55993, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56273, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56127, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56029, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56116, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56004, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56188, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56254, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56050, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56259, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56025, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56009, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56289, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56001, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56280, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56125, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56298, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56193, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55970, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55945, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56049, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56176, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55994, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55810, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56020, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55905, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55912, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56097, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55893, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55852, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56981, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56246, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55904, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56218, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56217, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56120, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55853, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56115, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56000, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56233, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55983, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55917, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56037, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56228, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55987, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56303, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56183, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56114, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56158, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56034, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56279, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55965, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56003, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56210, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55854, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55809, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56019, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56056, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55947, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55974, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56291, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56069, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55855, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56261, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56264, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55964, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56106, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56122, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56015, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56301, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55856, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55975, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55804, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55857, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56063, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55872, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55932, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55858, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56175, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55955, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56084, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56153, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55933, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56234, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55871, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55859, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56239, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55860, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56149, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56090, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56053, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56124, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56007, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55985, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56227, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56018, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56135, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56174, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55861, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55862, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56002, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55924, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56256, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55863, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55929, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55865, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55923, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56295, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55812, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 55915, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 56131, billingAddressee: 'United Rentals', shippingAddressee: 'United Rentals' },
    { internalId: 48556, billingAddressee: 'Uniti Fiber LLC', shippingAddressee: 'Uniti Fiber LLC' },
    { internalId: 48557, billingAddressee: 'Uniti Group LLC', shippingAddressee: 'Uniti Group LLC' },
    { internalId: 48558, billingAddressee: 'University Health', shippingAddressee: 'University Health' },
    { internalId: 54035, billingAddressee: 'University Health', shippingAddressee: 'University Health' },
    { internalId: 48559, billingAddressee: 'University of Houston-Dntn', shippingAddressee: 'University of Houston-Dntn' },
    { internalId: 56307, billingAddressee: 'University of Houston-Dntn', shippingAddressee: 'University of Houston-Dntn' },
    { internalId: 56306, billingAddressee: 'University of Houston-Dntn', shippingAddressee: 'University of Houston-Dntn' },
    { internalId: 48560, billingAddressee: 'UPS Fuel Services, Inc', shippingAddressee: 'UPS Fuel Services, Inc' },
    { internalId: 48645, billingAddressee: 'UPS Fuel Services, Inc', shippingAddressee: 'UPS Fuel Services, Inc' },
    { internalId: 48561, billingAddressee: 'USA Comserv', shippingAddressee: 'USA Comserv' },
    { internalId: 56939, billingAddressee: 'USA Rare Earth Magnets', shippingAddressee: 'USA Rare Earth Magnets' },
    { internalId: 48562, billingAddressee: 'USW-Menard, Inc', shippingAddressee: 'USW-Menard, Inc' },
    { internalId: 48563, billingAddressee: 'Utility Supply and Construction Company', shippingAddressee: 'Utility Supply and Construction Company' },
    { internalId: 56977, billingAddressee: 'Utility Supply and Construction Company', shippingAddressee: 'Utility Supply and Construction Company' },
    { internalId: 48564, billingAddressee: 'Valley Fence Company', shippingAddressee: 'Valley Fence Company' },
    { internalId: 48565, billingAddressee: 'Valvtechnologies LLC', shippingAddressee: 'Valvtechnologies LLC' },
    { internalId: 56308, billingAddressee: 'Valvtechnologies LLC', shippingAddressee: 'Valvtechnologies LLC' },
    { internalId: 48566, billingAddressee: 'Veloz Logistics', shippingAddressee: 'Veloz Logistics' },
    { internalId: 56310, billingAddressee: 'Veloz Logistics', shippingAddressee: 'Veloz Logistics' },
    { internalId: 56309, billingAddressee: 'Veloz Logistics', shippingAddressee: 'Veloz Logistics' },
    { internalId: 48567, billingAddressee: 'Venture Metals, L.L.C.', shippingAddressee: 'Venture Metals, L.L.C.' },
    { internalId: 56311, billingAddressee: 'Venture Metals, L.L.C.', shippingAddressee: 'Venture Metals, L.L.C.' },
    { internalId: 48568, billingAddressee: 'Verizon Business Purchasing', shippingAddressee: 'Verizon Business Purchasing' },
    { internalId: 48569, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56334, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56340, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56344, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56365, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56315, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56323, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56312, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56329, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56354, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56316, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56359, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56375, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56357, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56368, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56351, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56345, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56338, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56360, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56324, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56367, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56353, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56319, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56336, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56373, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56363, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56317, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56332, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56362, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56348, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56355, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56371, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56356, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56358, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56349, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56350, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56370, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56369, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56378, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56343, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56352, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56346, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56313, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56337, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56314, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56335, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56361, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56325, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56376, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56339, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56320, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56318, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56330, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56364, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56366, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56372, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56321, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56326, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56328, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56327, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56331, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56342, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56341, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56374, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56322, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56377, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56347, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 56333, billingAddressee: 'Verizon Global', shippingAddressee: 'Verizon Global' },
    { internalId: 48570, billingAddressee: 'Verne L  Willits', shippingAddressee: 'Verne L  Willits' },
    { internalId: 56916, billingAddressee: 'Villages at Woodlands', shippingAddressee: 'Villages at Woodlands' },
    { internalId: 48571, billingAddressee: 'Vixxo Kansas, LLC', shippingAddressee: 'Vixxo Kansas, LLC' },
    { internalId: 56379, billingAddressee: 'Vixxo Kansas, LLC', shippingAddressee: 'Vixxo Kansas, LLC' },
    { internalId: 48692, billingAddressee: 'Vizion Crane & Industrial Support, LLC', shippingAddressee: 'Vizion Crane & Industrial Support, LLC' },
    { internalId: 48572, billingAddressee: 'VOA Lee County Health Care Facility, Inc', shippingAddressee: 'VOA Lee County Health Care Facility, Inc' },
    { internalId: 48573, billingAddressee: 'VoltaGrid LLC', shippingAddressee: 'VoltaGrid LLC' },
    { internalId: 56385, billingAddressee: 'VoltaGrid LLC', shippingAddressee: 'VoltaGrid LLC' },
    { internalId: 56384, billingAddressee: 'VoltaGrid LLC', shippingAddressee: 'VoltaGrid LLC' },
    { internalId: 56383, billingAddressee: 'VoltaGrid LLC', shippingAddressee: 'VoltaGrid LLC' },
    { internalId: 56381, billingAddressee: 'VoltaGrid LLC', shippingAddressee: 'VoltaGrid LLC' },
    { internalId: 56382, billingAddressee: 'VoltaGrid LLC', shippingAddressee: 'VoltaGrid LLC' },
    { internalId: 56380, billingAddressee: 'VoltaGrid LLC', shippingAddressee: 'VoltaGrid LLC' },
    { internalId: 56386, billingAddressee: 'VoltaGrid LLC', shippingAddressee: 'VoltaGrid LLC' },
    { internalId: 56387, billingAddressee: 'VoltaGrid LLC', shippingAddressee: 'VoltaGrid LLC' },
    { internalId: 48574, billingAddressee: 'Vortex Lining Systems, LLC', shippingAddressee: 'Vortex Lining Systems, LLC' },
    { internalId: 56389, billingAddressee: 'Vortex Lining Systems, LLC', shippingAddressee: 'Vortex Lining Systems, LLC' },
    { internalId: 56388, billingAddressee: 'Vortex Lining Systems, LLC', shippingAddressee: 'Vortex Lining Systems, LLC' },
    { internalId: 48575, billingAddressee: 'W&W Steel Erectors LLC', shippingAddressee: 'W&W Steel Erectors LLC' },
    { internalId: 48576, billingAddressee: 'W.E. Bowers & Associates, Inc.', shippingAddressee: 'W.E. Bowers & Associates, Inc.' },
    { internalId: 48577, billingAddressee: 'W.M. Schultz Construction Inc.', shippingAddressee: 'W.M. Schultz Construction Inc.' },
    { internalId: 48738, billingAddressee: 'W.R. Newman & Associates, Inc', shippingAddressee: 'W.R. Newman & Associates, Inc' },
    { internalId: 48578, billingAddressee: 'W.T. Byler Co., Inc', shippingAddressee: 'W.T. Byler Co., Inc' },
    { internalId: 56390, billingAddressee: 'W.T. Byler Co., Inc', shippingAddressee: 'W.T. Byler Co., Inc' },
    { internalId: 56391, billingAddressee: 'W.T. Byler Co., Inc', shippingAddressee: 'W.T. Byler Co., Inc' },
    { internalId: 48580, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56411, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56956, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56397, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56406, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56407, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56398, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56399, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56403, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56409, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56410, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56408, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56404, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56402, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56400, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56955, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56393, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56405, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56396, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56412, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56401, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56395, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56392, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 56394, billingAddressee: 'Wal-Mart Stores, Inc', shippingAddressee: 'Wal-Mart Stores, Inc' },
    { internalId: 48579, billingAddressee: 'Wallace Controls & Electric, Inc.', shippingAddressee: 'Wallace Controls & Electric, Inc.' },
    { internalId: 48736, billingAddressee: 'Wallace Williford Inc.', shippingAddressee: 'Wallace Williford Inc.' },
    { internalId: 48581, billingAddressee: 'Waste Management', shippingAddressee: 'Waste Management' },
    { internalId: 48582, billingAddressee: 'Waste Services of Texas LLC-Cleveland', shippingAddressee: 'Waste Services of Texas LLC-Cleveland' },
    { internalId: 56413, billingAddressee: 'Waste Services of Texas LLC-Cleveland', shippingAddressee: 'Waste Services of Texas LLC-Cleveland' },
    { internalId: 48583, billingAddressee: 'Watco', shippingAddressee: 'Watco' },
    { internalId: 48584, billingAddressee: 'Watterson Environmental Group, LLC', shippingAddressee: 'Watterson Environmental Group, LLC' },
    { internalId: 48585, billingAddressee: 'Waukesha-Pearce Industries', shippingAddressee: 'Waukesha-Pearce Industries' },
    { internalId: 56414, billingAddressee: 'Waukesha-Pearce Industries', shippingAddressee: 'Waukesha-Pearce Industries' },
    { internalId: 56431, billingAddressee: 'Waukesha-Pearce Industries', shippingAddressee: 'Waukesha-Pearce Industries' },
    { internalId: 56418, billingAddressee: 'Waukesha-Pearce Industries', shippingAddressee: 'Waukesha-Pearce Industries' },
    { internalId: 56429, billingAddressee: 'Waukesha-Pearce Industries', shippingAddressee: 'Waukesha-Pearce Industries' },
    { internalId: 56416, billingAddressee: 'Waukesha-Pearce Industries', shippingAddressee: 'Waukesha-Pearce Industries' },
    { internalId: 56424, billingAddressee: 'Waukesha-Pearce Industries', shippingAddressee: 'Waukesha-Pearce Industries' },
    { internalId: 56423, billingAddressee: 'Waukesha-Pearce Industries', shippingAddressee: 'Waukesha-Pearce Industries' },
    { internalId: 56428, billingAddressee: 'Waukesha-Pearce Industries', shippingAddressee: 'Waukesha-Pearce Industries' },
    { internalId: 56422, billingAddressee: 'Waukesha-Pearce Industries', shippingAddressee: 'Waukesha-Pearce Industries' },
    { internalId: 56427, billingAddressee: 'Waukesha-Pearce Industries', shippingAddressee: 'Waukesha-Pearce Industries' },
    { internalId: 56426, billingAddressee: 'Waukesha-Pearce Industries', shippingAddressee: 'Waukesha-Pearce Industries' },
    { internalId: 56421, billingAddressee: 'Waukesha-Pearce Industries', shippingAddressee: 'Waukesha-Pearce Industries' },
    { internalId: 56420, billingAddressee: 'Waukesha-Pearce Industries', shippingAddressee: 'Waukesha-Pearce Industries' },
    { internalId: 56425, billingAddressee: 'Waukesha-Pearce Industries', shippingAddressee: 'Waukesha-Pearce Industries' },
    { internalId: 56419, billingAddressee: 'Waukesha-Pearce Industries', shippingAddressee: 'Waukesha-Pearce Industries' },
    { internalId: 56430, billingAddressee: 'Waukesha-Pearce Industries', shippingAddressee: 'Waukesha-Pearce Industries' },
    { internalId: 56415, billingAddressee: 'Waukesha-Pearce Industries', shippingAddressee: 'Waukesha-Pearce Industries' },
    { internalId: 56957, billingAddressee: 'Waukesha-Pearce Industries', shippingAddressee: 'Waukesha-Pearce Industries' },
    { internalId: 56432, billingAddressee: 'Waukesha-Pearce Industries', shippingAddressee: 'Waukesha-Pearce Industries' },
    { internalId: 56417, billingAddressee: 'Waukesha-Pearce Industries', shippingAddressee: 'Waukesha-Pearce Industries' },
    { internalId: 48586, billingAddressee: 'Weeks Marine, Inc 11354758101', shippingAddressee: 'Weeks Marine, Inc 11354758101' },
    { internalId: 48587, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56489, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56483, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56531, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56493, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56439, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56434, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56435, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56436, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56450, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56523, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56485, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56539, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56514, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56538, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56446, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56475, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56484, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56471, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56486, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56501, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56504, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56474, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56476, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56545, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56546, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56494, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56502, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56495, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56500, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56507, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56516, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56522, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56537, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56511, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56497, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56526, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56488, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56505, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56508, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56530, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56490, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56529, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56515, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56437, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56438, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56458, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56442, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56481, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56519, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56466, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56506, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56443, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56453, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56540, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56517, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56496, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56541, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56491, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56499, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56503, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56513, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56512, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56518, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56536, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56482, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56532, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56520, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56525, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56444, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56509, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56521, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56498, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56534, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56535, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56487, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56492, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56465, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56462, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56463, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56454, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56467, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56478, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56451, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56440, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56456, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56452, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56441, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56528, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56455, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56457, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56459, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56449, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56445, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56469, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56477, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56464, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56470, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56543, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56527, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56542, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56524, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56480, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56473, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56479, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56461, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56472, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56510, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56447, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56544, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56468, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56448, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56533, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56460, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 56433, billingAddressee: 'Weisinger Incorporated', shippingAddressee: 'Weisinger Incorporated' },
    { internalId: 48588, billingAddressee: 'Wellbore Fishing & Rental Tool', shippingAddressee: 'Wellbore Fishing & Rental Tool' },
    { internalId: 56548, billingAddressee: 'Wellbore Fishing & Rental Tool', shippingAddressee: 'Wellbore Fishing & Rental Tool' },
    { internalId: 56547, billingAddressee: 'Wellbore Fishing & Rental Tool', shippingAddressee: 'Wellbore Fishing & Rental Tool' },
    { internalId: 48589, billingAddressee: 'Wellbore Services, LLC', shippingAddressee: 'Wellbore Services, LLC' },
    { internalId: 56550, billingAddressee: 'Wellbore Services, LLC', shippingAddressee: 'Wellbore Services, LLC' },
    { internalId: 56549, billingAddressee: 'Wellbore Services, LLC', shippingAddressee: 'Wellbore Services, LLC' },
    { internalId: 48590, billingAddressee: 'West Janisch Health Care Center', shippingAddressee: 'West Janisch Health Care Center' },
    { internalId: 48591, billingAddressee: 'Western Rim Investors 2014-1, LP', shippingAddressee: 'Western Rim Investors 2014-1, LP' },
    { internalId: 48592, billingAddressee: 'Western States Drilling and Blasting Inc.', shippingAddressee: 'Western States Drilling and Blasting Inc.' },
    { internalId: 48593, billingAddressee: 'WET Services', shippingAddressee: 'WET Services' },
    { internalId: 56551, billingAddressee: 'WET Services', shippingAddressee: 'WET Services' },
    { internalId: 48594, billingAddressee: 'WG Wade Shows Inc', shippingAddressee: 'WG Wade Shows Inc' },
    { internalId: 48595, billingAddressee: 'Whistlin Diesel LLC, shippingAddressee: Whistlin Diesel LLC'},
    { internalId: 48596, billingAddressee: 'Whole Foods Market Inc', shippingAddressee: 'Whole Foods Market Inc' },
    { internalId: 48688, billingAddressee: 'Wiginton Corporation', shippingAddressee: 'Wiginton Corporation' },
    { internalId: 48597, billingAddressee: 'Will Call', shippingAddressee: 'Will Call' },
    { internalId: 56893, billingAddressee: 'Williamsburg Health & Rehabilitation', shippingAddressee: 'Williamsburg Health & Rehabilitation' },
    { internalId: 48647, billingAddressee: 'Wingate Residences on Blackstone Blvd', shippingAddressee: 'Wingate Residences on Blackstone Blvd' },
    { internalId: 48598, billingAddressee: 'WM Shipping Services Inc', shippingAddressee: 'WM Shipping Services Inc' },
    { internalId: 56552, billingAddressee: 'WM Shipping Services Inc', shippingAddressee: 'WM Shipping Services Inc' },
    { internalId: 48683, billingAddressee: 'Womens Hospital of Texas', shippingAddressee: 'Womens Hospital of Texas' },
    { internalId: 56553, billingAddressee: 'Womens Hospital of Texas', shippingAddressee: 'Womens Hospital of Texas' },
    { internalId: 48599, billingAddressee: 'Woodforest National Bank', shippingAddressee: 'Woodforest National Bank' },
    { internalId: 48600, billingAddressee: 'World Central Kitchen, Inc', shippingAddressee: 'World Central Kitchen, Inc' },
    { internalId: 48601, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56578, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56561, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56603, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56584, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56619, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56583, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56594, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56616, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56613, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56615, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56605, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56597, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56589, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56585, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56598, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56610, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56602, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56596, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56560, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56609, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56574, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56591, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56555, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56562, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56581, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56577, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56580, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56571, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56569, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56556, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56595, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56575, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56566, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56572, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56614, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56567, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56612, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56588, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56564, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56611, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56590, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56586, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56568, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56606, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56582, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56587, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56563, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56592, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56600, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56557, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56622, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56558, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56593, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56554, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56570, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56599, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56573, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56604, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56607, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56617, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56621, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56601, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56608, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56620, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56576, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56618, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56579, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56559, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 56565, billingAddressee: 'WorldwidePower Products, LLC', shippingAddressee: 'WorldwidePower Products, LLC' },
    { internalId: 48602, billingAddressee: 'WPL Fab, LLC', shippingAddressee: 'WPL Fab, LLC' },
    { internalId: 48603, billingAddressee: 'Xtreme Construction & Remodeling LLC', shippingAddressee: 'Xtreme Construction & Remodeling LLC' },
    { internalId: 48734, billingAddressee: 'Yaniec Elite Sercies, LLC', shippingAddressee: 'Yaniec Elite Sercies, LLC' },
    { internalId: 48604, billingAddressee: 'Yellow Brick Nursery', shippingAddressee: 'Yellow Brick Nursery' },
    { internalId: 48605, billingAddressee: 'Zebra Recovery LLC', shippingAddressee: 'Zebra Recovery LLC' },
    { internalId: 48606, billingAddressee: 'Zoomlion Heavy Industry NA, Inc.', shippingAddressee: 'Zoomlion Heavy Industry NA, Inc.' },
    { internalId: 48607, billingAddressee: 'ZPMC NA East Coast Inc', shippingAddressee: 'ZPMC NA East Coast Inc' },
    { internalId: 56623, billingAddressee: 'ZPMC NA East Coast Inc', shippingAddressee: 'ZPMC NA East Coast Inc' }
];

        
    };

    const map = (context) => {
        try {
            const data = JSON.parse(context.value);
            const customerId = data.internalId;
            const billingAddressee = data.billingAddressee;
            const shippingAddressee = data.shippingAddressee;

            log.debug('Processing Customer', customerId);

            const customerRec = record.load({
                type: record.Type.CUSTOMER,
                id: customerId,
                isDynamic: true
            });

            const lineCount = customerRec.getLineCount({ sublistId: 'addressbook' });

            for (let i = 0; i < lineCount; i++) {
                customerRec.selectLine({ sublistId: 'addressbook', line: i });

                const addressSubRec = customerRec.getCurrentSublistSubrecord({
                    sublistId: 'addressbook',
                    fieldId: 'addressbookaddress'
                });

                const defaultBilling = customerRec.getCurrentSublistValue({
                    sublistId: 'addressbook',
                    fieldId: 'defaultbilling'
                });

                const defaultShipping = customerRec.getCurrentSublistValue({
                    sublistId: 'addressbook',
                    fieldId: 'defaultshipping'
                });

                // Update Billing Addressee
                if (defaultBilling && billingAddressee) {
                    addressSubRec.setValue({
                        fieldId: 'addressee',
                        value: billingAddressee
                    });
                    log.debug('Billing Updated', billingAddressee);
                }

                // Update Shipping Addressee
                if (defaultShipping && shippingAddressee) {
                    addressSubRec.setValue({
                        fieldId: 'addressee',
                        value: shippingAddressee
                    });
                    log.debug('Shipping Updated', shippingAddressee);
                }

                customerRec.commitLine({ sublistId: 'addressbook' });
            }

            const customerIdSaved = customerRec.save({ enableSourcing: true, ignoreMandatoryFields: true });
            log.audit('Customer Updated', `Internal ID: ${customerIdSaved}`);

        } catch (e) {
            log.error('Error Updating Customer', e);
        }
    };

    const summarize = (summary) => {
        summary.mapSummary.errors.iterator().each((key, error) => {
            log.error('Map Error for key: ' + key, error);
            return true;
        });
        log.audit('Script Complete', 'All records processed.');
    };

    return { getInputData, map, summarize };
});
